#!/bin/bash

# 🦊 GitLab Setup Instructions for samba425-group

echo "🦊 GitLab Deployment Setup"
echo "==========================="
echo ""
echo "STEP 1: Create Repository on GitLab"
echo "------------------------------------"
echo "1. Go to: https://gitlab.com/samba425-group"
echo "2. Click 'New project' → 'Create blank project'"
echo "3. Project name: tech-mastery-notebooks"
echo "4. Visibility: Public"
echo "5. Uncheck 'Initialize repository with a README'"
echo "6. Click 'Create project'"
echo ""
echo "STEP 2: Set Up Authentication"
echo "------------------------------"
echo "Choose ONE option:"
echo ""
echo "A) Use HTTPS with Personal Access Token (Recommended)"
echo "   1. Go to: https://gitlab.com/-/profile/personal_access_tokens"
echo "   2. Click 'Add new token'"
echo "   3. Name: deployment-token"
echo "   4. Check scope: 'write_repository'"
echo "   5. Click 'Create personal access token'"
echo "   6. Copy the token"
echo ""
echo "   Then run:"
echo "   git remote remove gitlab"
echo "   git remote add gitlab https://oauth2:YOUR_TOKEN@gitlab.com/samba425-group/tech-mastery-notebooks.git"
echo "   git push gitlab main"
echo ""
echo "B) Use SSH (Alternative)"
echo "   1. Go to: https://gitlab.com/-/profile/keys"
echo "   2. Add your SSH key"
echo "   3. Then run:"
echo "   git remote remove gitlab"
echo "   git remote add gitlab git@gitlab.com:samba425-group/tech-mastery-notebooks.git"
echo "   git push gitlab main"
echo ""
echo "STEP 3: Verify Deployment"
echo "-------------------------"
echo "After successful push:"
echo "1. Go to: https://gitlab.com/samba425-group/tech-mastery-notebooks"
echo "2. Click 'CI/CD' → 'Pipelines'"
echo "3. Wait for green checkmark (3-5 minutes)"
echo "4. Go to 'Settings' → 'Pages'"
echo "5. Your site: https://samba425-group.gitlab.io/tech-mastery-notebooks/"
echo ""
echo "🎉 Your site will be LIVE!"
